contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact, name='contact'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('profile', views.userProfile, name='profile'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.list, name='list'),
]

contacts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

class Product(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    sale_price = models.IntegerField(null=True,blank=True)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ('title','slug')

    def get_price(self):
        return self.price


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d/')
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product.title

contacts/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=200,
                            help_text='Username is required',
                            required=True,)
    email = forms.EmailField(max_length=100,
                            label='Sender',
                            help_text='E.g., "me@example.com"')
    comment = forms.CharField(max_length=200,widget=forms.Textarea(attrs={
        'rows':'5',
        'placeholder':'Leave Comment',
    }))


    # name = forms.CharField(max_length=200,
    #                         widget=forms.TextInput(attrs={
    #                             'required':'False',
    #                             'class':'form-control',
    #                             'placeholder':'Enter Username',
    #                             'help_text':'100 characters max',
    #                         }))
    # email = forms.EmailField(max_length=100,
    #                         widget=forms.EmailInput(attrs={
    #                                 'required':'True',
    #                                 'class':'form-control',
    #                                 'placeholder':'Enter Email'
    #                           }))
    # comment = forms.CharField(max_length=200,
    #                             widget=forms.Textarea(attrs={
    #                                 'rows':'6',
    #                                 'required':'True',
    #                                 'class':'form-control',
    #                                 'placeholder':'Comment here'
    #                           }))

contacts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from . import forms

def contact(request):
    if request.method == 'POST':
        form = forms.ContactForm(request.POST or None)
        if form.is_valid():
            name = form.cleaned_data['name']
            comment = form.cleaned_data['comment']
            subject = 'Message from MYSITE.com'
            message =  '%s %s' %(comment, name)
            emailFrom = form.cleaned_data['email']
            emailTo = [settings.EMAIL_HOST_USER]
        form = False
        title = 'Thanks!'
        context = {'title':title, 'form':form}    
        messages.success(request, 'Thanks for the message. We will get right back to you.')
        return render(request, 'contacts/contact.html', context)
    else:
        title = 'Contact'
        form = forms.ContactForm()
        context = {'title':title, 'form':form}
        return render(request,'contacts/contact.html', context)

pages/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

def home(request):
	return render(request,'pages/home.html')

def about(request):
    return render(request,'pages/about.html')

@login_required
def userProfile(request):
    user = request.user
    context = {'user':user}
    return render(request,'pages/profile.html',context)



    

products/views.py
from django.shortcuts import render

from .models import Product

def list(request):
    products = Product.objects.all()

    context = {"products": products}

    return  render(request, 'products/index.html', context)

templates/accounts/login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% load bootstrap4 %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<div class="col-md-4 mx-auto">

    <h1>{% trans "Sign In" %}</h1>

    {% get_providers as socialaccount_providers %}

    {% if socialaccount_providers %}
    <p>{% blocktrans with site.name as site_name %}Please sign in with one
    of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
    for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

    <div class="socialaccount_ballot">

    <ul class="socialaccount_providers">
        {% include "socialaccount/snippets/provider_list.html" with process="login" %}
    </ul>

    <div class="login-or">{% trans 'or' %}</div>

    </div>

    {% include "socialaccount/snippets/login_extra.html" %}

    {% else %}
    <p>{% blocktrans %}If you have not created an account yet, then please
    <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
    {% endif %}

    <form class="login" method="POST" action="{% url 'account_login' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
        <a class="btn btn-link button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
        <button class="primaryAction btn btn-info btn-block" type="submit">{% trans "Sign In" %}</button>
    </form>

</div>

{% endblock %}

templates/accounts/logout.html
{% extends "account/base.html" %}

{% load i18n %}
{% load bootstrap4 %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<div class="col-md-4 mx-auto">

  <h1>{% trans "Sign Out" %}</h1>

  <p>{% trans 'Are you sure you want to sign out?' %}</p>

  <form method="post" action="{% url 'account_logout' %}">
    {% csrf_token %}
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <button type="submit" class="btn btn-secondary">{% trans 'Sign Out' %}</button>
  </form>

</div>

{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block content %}
<div class="col-md-4 mx-auto">

    <h1>{% trans "Sign Up" %}</h1>

    <p>{% blocktrans %}Already have an account? Then please <a href="{{ login_url }}">sign in</a>.{% endblocktrans %}</p>

    <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
        <button type="submit" class="btn btn-primary"{% trans "Sign Up" %} &raquo;</button>
    </form>

</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Lightbox -->
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
    {% block style %}{% endblock %}

    <title>CFE STORE {% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}

    <div class="container theme-showcase" role="main">
        {% block jumbotron %}
        {% endblock %}

        {% block content %} 
        {% endblock %}

    </div>

    <!-- Footer -->
    {% include 'partials/_footer.html' %}

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block jquery %}{% endblock %}
</body>

</html>



    

templates/contacts/contact.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
        <div class="row">
            <div class="col-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-white px-2 py-1">
                        <h3>{{ title }}</h3>
                    </div>
                    <div class="card-body">
                        {% if confirm_message %}
                        <div class="card bg-success">
                            <p class="card-title text-center text-white pt-1">{{ confirm_message }}</p>
                        </div>
                        {% endif %}
                        {% if form %}
                        <form action="{% url 'contacts:contact' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}                            
                            <div class="row">
                                <div class="col-md-12">
                                    {%  bootstrap_field form.name addon_before='<i class="fas fa-user" aria-hidden="true"></i>' %}
                                </div>
                                <div class="col-md-12">
                                    {%  bootstrap_field form.email %}
                                </div>
                                <div class="col-md-12">
                                    {%  bootstrap_field form.comment %}
                                </div>
                            </div>
                            {%  if form.maybemissing %}
                            {%  bootstrap_field form.maybemissing %}
                            {%  endif %}
                            <a class="btn btn-secondary" href="{% url 'pages:home' %}">Cancel</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                        {% else %}
                            <!-- Alerts -->
                            {% include 'partials/_alerts.html' %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    
{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}

{% block style %}
<style>
    .jumbotron {
        text-align: center;
    }
</style>
{% endblock %}

{% block jumbotron %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1>About Us</h1>
    <p>This is a aboutus template.</p>
</div>
{% endblock %}

{% block content %}
<h1>Welcome home!</h1>
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}

{% block style %}
<style>
    .jumbotron {
        text-align: center;
    }
</style>
{% endblock %}

{% block jumbotron %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1>Theme example</h1>
    <p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to
        create something more unique by building on or modifying it.</p>
</div>
{% endblock %}

{% block content %}
<h1>Hello world!</h1>
{% endblock %}

templates/pages/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <p>{{ user.email }}</p>
{% endblock %}

templates/partials/_alerts.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container text-center">
    <div class="alert alert-dismissable alert-{{ message.tags }}">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-md fixed-top navbar-light bg-light mb-5 py-0">
    <div class="container">
        <a class="navbar-brand" href="{% url 'pages:home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% url 'pages:home' as home %}
                {% url 'pages:about' as about %}
                {% url 'products:list' as product %}
                {% url 'contacts:contact' as contact %}
                {% url 'account_login' as login %}
                {% url 'account_logout' as logout %}
                {% url 'account_signup' as signup %}
                <li class="nav-item {% if request.path == home %} active {% endif %}">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                </li>
                <li class="nav-item {% if request.path == product %} active {% endif %}">
                    <a class="nav-link" href="{% url 'products:list' %}">Products</a>
                </li>
                <li class="nav-item {% if request.path == about %} active {% endif %}">
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>
                <li class="nav-item {% if request.path == contact %} active {% endif %}">
                    <a class="nav-link" href="{% url 'contacts:contact' %}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == contact %} active {% endif %}">
                    <a class="nav-link" href="{% url 'pages:profile' %}">Profile</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == logout %} active {% endif %}">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == login %} active {% endif %}">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item {% if request.path == signup %} active {% endif %}">
                        <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
            <!-- <form class="form-inline mt-2 mt-md-0">
                <input class="form-control form-control-sm mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>
    </div>
</nav>
<hr class="mb-5">

templates/products/index.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} | Welcome {% endblock %}

{% block style %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <!-- <div class="jumbotron">
        <h1>Navbar example</h1>
        <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you
            scroll, this navbar remains in its original position and moves with the rest of the page.</p>
        <a class="btn btn-lg btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
    </div> -->
    <div class="container">
        <div class="row">
            <!-- <div class="col-sm-12"> -->
                <h3 class="col-12">Products Lists</h3>
                <hr>
                {% if products %}
                    {% for product in products %}
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card listing-preview">
                                {% for item in product.productimage_set.all %}
                                    <img class="card-img-top" src="{{ item.image.url }}" alt="">
                                {% endfor %}
                                <div class="card-img-overlay">
                                    <h2>
                                        <span class="badge badge-secondary text-white">Sh{{ product.price | intcomma }}</span>
                                    </h2>
                                </div>
                                <div class="card-body">
                                    <div class="listing-heading text-center">
                                        <h4 class="text-primary">{{ product.title }}</h4>
                                    </div>
                                    <!-- <div class="row py-2 text-secondary">
                                         {{ product.description }}
                                    </div> -->
                                    <div class="row text-secondary px-2">
                                        <i class="fa fa-clock"></i> {{ product.created_at | timesince }}
                                    </div>
                                    <hr>
                                    <a href="#" class="btn btn-primary btn-block">More Info</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <p class="card-title">No Product Available</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block jquery %}
    <script>
        //$(document).ready(function(){
          //  alert('hello')
        //});
    </script>
{% endblock %}